version: '3.3'

services:
  database:
    container_name: drink-manager-db
    image: alexstancu96/drink-manager-db:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - back-tier
    volumes:
      - drink-data:/var/lib/mysql

  backend-app:
    container_name: drink-manager-rest
    image: alexstancu96/drink-manager-rest:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - back-tier
      - front-tier

  frontend-app:
    container_name: drink-manager-ui
    image: alexstancu96/drink-manager-ui:latest
    restart: always
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "4200:4200"
    depends_on:
    - backend-app
    networks:
      - front-tier

networks:
  back-tier:
  front-tier:

volumes:
  drink-data:
